archive_dir: archives
author: 元素
category_dir: categories
category_map:
  学科: subject
  数学: mathematics
  数据结构: data-structure
  算法: algorithm
  编程: programming
code_dir: downloads/code
date_format: YYYY-MM-DD
default_category: 未分类
default_layout: post
deploy:
  branch: gh-pages
  ignore_hidden: false
  repo: https://github.com/originalFactor/ptoe.cc
  type: git
description: 只是一个臭写算法的
exclude: null
external_link:
  enable: true
  exclude:
  - ptoe.cc
  - www.ptoe.cc
  field: site
feed:
  autodiscovery: true
  content: null
  content_limit: 140
  content_limit_delim: ' '
  enable: true
  hub: null
  icon: icon.png
  limit: 20
  order_by: -date
  path: atom.xml
  template: null
  type: atom
filename_case: 1
future: true
highlight:
  auto_detect: false
  hljs: false
  line_number: true
  tab_replace: '    '
  wrap: true
i18n_dir: :lang
ignore: null
include:
- .nojekyll
index_generator:
  order_by: -date
  path: ''
  per_page: 10
keywords:
- C++
- 算法
- Python
language: zh-CN
meta_generator: true
new_post_name: :year/:month/:day/:title.md
pagination_dir: page
per_page: 10
permalink: :year/:month/:day/:title.html
permalink_defaults: null
post_asset_folder: false
pretty_urls:
  trailing_html: true
  trailing_index: false
prismjs:
  line_number: true
  preprocess: true
  tab_replace: ''
public_dir: public
relative_link: false
render_drafts: false
skip_render:
- .nojekyll
source_dir: source
subtitle: 技术创造新生
syntax_highlighter: highlight.js
tag-generator:
  enable_index_page: false
tag_dir: tags
tag_map:
  C++: cpp
  CSP-J: csp-j
  GESP: gesp
  NOIP: noip
  Python: python
  三角函数: trigonometry
  位运算: bit-manipulation
  几何: geometry
  动态规划: dynamic-programming
  区间覆盖: interval-coverage
  单调栈: monotonic-stack
  图论: graph-theory
  归并排序: merge-sort
  排序算法: sorting-algorithm
  插入排序: insertion-sort
  数学: mathematics
  数据结构: data-structure
  最大瓶颈路: maximum-bottleneck-path
  最短路: shortest-path
  最长上升子序列: longest-increasing-subsequence
  树: tree
  模拟: simulation
  深度优先搜索: depth-first-search
  立体几何: solid-geometry
  算法: algorithm
  编程: programming
  贪心算法: greedy-algorithm
  递归: recursion
theme: next
time_format: HH:mm:ss
timezone: Asia/Shanghai
title: 元素的笔记
titlecase: false
updated_option: mtime
url: https://www.ptoe.cc/
